# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.8)
   message(FATAL_ERROR "CMake >= 2.8.0 required")
endif()
if(CMAKE_VERSION VERSION_LESS "2.8.3")
   message(FATAL_ERROR "CMake >= 2.8.3 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.8.3...3.25)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_cmake_targets_defined "")
set(_cmake_targets_not_defined "")
set(_cmake_expected_targets "")
foreach(_cmake_expected_target IN ITEMS protodunedm::HepMCFileGen_module protodunedm::ProtoDUNEDMAnalyze_module protodunedm::TriggerPrimitiveProtoDUNE_module)
  list(APPEND _cmake_expected_targets "${_cmake_expected_target}")
  if(TARGET "${_cmake_expected_target}")
    list(APPEND _cmake_targets_defined "${_cmake_expected_target}")
  else()
    list(APPEND _cmake_targets_not_defined "${_cmake_expected_target}")
  endif()
endforeach()
unset(_cmake_expected_target)
if(_cmake_targets_defined STREQUAL _cmake_expected_targets)
  unset(_cmake_targets_defined)
  unset(_cmake_targets_not_defined)
  unset(_cmake_expected_targets)
  unset(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT _cmake_targets_defined STREQUAL "")
  string(REPLACE ";" ", " _cmake_targets_defined_text "${_cmake_targets_defined}")
  string(REPLACE ";" ", " _cmake_targets_not_defined_text "${_cmake_targets_not_defined}")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_cmake_targets_defined_text}\nTargets not yet defined: ${_cmake_targets_not_defined_text}\n")
endif()
unset(_cmake_targets_defined)
unset(_cmake_targets_not_defined)
unset(_cmake_expected_targets)


# Create imported target protodunedm::HepMCFileGen_module
add_library(protodunedm::HepMCFileGen_module SHARED IMPORTED)

set_target_properties(protodunedm::HepMCFileGen_module PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/build_slf7.x86_64/protodunedm;/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/srcs/protodunedm"
  INTERFACE_LINK_LIBRARIES "larcore::ServiceUtil;larcore::Geometry_Geometry_service;larcorealg::Geometry;larcoreobj::SummaryData;larcoreobj::SimpleTypesAndConstants;lardataobj::RecoBase;lardataobj::Simulation;larsim::Simulation;nusimdata::SimulationBase;art::Framework_Core;art::Framework_Principal;art::Framework_Services_Registry;art::Persistency_Common;canvas::canvas;messagefacility::MF_MessageLogger;hep_concurrency::thread_sanitize;hep_concurrency::hep_concurrency;hep_concurrency::cache;hep_concurrency::simultaneous_function_spawner;fhiclcpp::fhiclcpp;fhiclcpp::types;cetlib::cetlib;cetlib_except::cetlib_except;ifdh::ifdh;art_root_io::tfile_support;ROOT::Core;ROOT::Hist;ROOT::Physics;ROOT::Tree;art_root_io::TFileService_service"
)

# Create imported target protodunedm::ProtoDUNEDMAnalyze_module
add_library(protodunedm::ProtoDUNEDMAnalyze_module SHARED IMPORTED)

set_target_properties(protodunedm::ProtoDUNEDMAnalyze_module PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/build_slf7.x86_64/protodunedm;/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/srcs/protodunedm"
  INTERFACE_LINK_LIBRARIES "larcore::ServiceUtil;larcore::Geometry_Geometry_service;larcorealg::Geometry;larcoreobj::SummaryData;larcoreobj::SimpleTypesAndConstants;lardataobj::RecoBase;lardataobj::Simulation;larsim::Simulation;nusimdata::SimulationBase;art::Framework_Core;art::Framework_Principal;art::Framework_Services_Registry;art::Persistency_Common;canvas::canvas;messagefacility::MF_MessageLogger;hep_concurrency::thread_sanitize;hep_concurrency::hep_concurrency;hep_concurrency::cache;hep_concurrency::simultaneous_function_spawner;fhiclcpp::fhiclcpp;fhiclcpp::types;cetlib::cetlib;cetlib_except::cetlib_except;ifdh::ifdh;art_root_io::tfile_support;ROOT::Core;ROOT::Hist;ROOT::Physics;ROOT::Tree;art_root_io::TFileService_service"
)

# Create imported target protodunedm::TriggerPrimitiveProtoDUNE_module
add_library(protodunedm::TriggerPrimitiveProtoDUNE_module SHARED IMPORTED)

set_target_properties(protodunedm::TriggerPrimitiveProtoDUNE_module PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/build_slf7.x86_64/protodunedm;/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/srcs/protodunedm"
  INTERFACE_LINK_LIBRARIES "larcore::ServiceUtil;larcore::Geometry_Geometry_service;larcorealg::Geometry;larcoreobj::SummaryData;larcoreobj::SimpleTypesAndConstants;lardataobj::RecoBase;lardataobj::Simulation;larsim::Simulation;nusimdata::SimulationBase;art::Framework_Core;art::Framework_Principal;art::Framework_Services_Registry;art::Persistency_Common;canvas::canvas;messagefacility::MF_MessageLogger;hep_concurrency::thread_sanitize;hep_concurrency::hep_concurrency;hep_concurrency::cache;hep_concurrency::simultaneous_function_spawner;fhiclcpp::fhiclcpp;fhiclcpp::types;cetlib::cetlib;cetlib_except::cetlib_except;ifdh::ifdh;art_root_io::tfile_support;ROOT::Core;ROOT::Hist;ROOT::Physics;ROOT::Tree;art_root_io::TFileService_service"
)

# Import target "protodunedm::HepMCFileGen_module" for configuration "RelWithDebInfo"
set_property(TARGET protodunedm::HepMCFileGen_module APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(protodunedm::HepMCFileGen_module PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/build_slf7.x86_64/protodunedm/slf7.x86_64.e26.prof/lib/libHepMCFileGen_module.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libHepMCFileGen_module.so"
  )

# Import target "protodunedm::ProtoDUNEDMAnalyze_module" for configuration "RelWithDebInfo"
set_property(TARGET protodunedm::ProtoDUNEDMAnalyze_module APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(protodunedm::ProtoDUNEDMAnalyze_module PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/build_slf7.x86_64/protodunedm/slf7.x86_64.e26.prof/lib/libProtoDUNEDMAnalyze_module.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libProtoDUNEDMAnalyze_module.so"
  )

# Import target "protodunedm::TriggerPrimitiveProtoDUNE_module" for configuration "RelWithDebInfo"
set_property(TARGET protodunedm::TriggerPrimitiveProtoDUNE_module APPEND PROPERTY IMPORTED_CONFIGURATIONS RELWITHDEBINFO)
set_target_properties(protodunedm::TriggerPrimitiveProtoDUNE_module PROPERTIES
  IMPORTED_LOCATION_RELWITHDEBINFO "/afs/cern.ch/work/p/psajitha/public/protodune/ProtoDUNE_BSM_LArSoft/build_slf7.x86_64/protodunedm/slf7.x86_64.e26.prof/lib/libTriggerPrimitiveProtoDUNE_module.so"
  IMPORTED_SONAME_RELWITHDEBINFO "libTriggerPrimitiveProtoDUNE_module.so"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
