###INCLUDE_BEGIN### /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in (2 passes)
########################################################################
# protodunedmConfig.cmake
#
#   Config for CMake project protodunedm 01.00.00.
#
# Generated by cetmodules 3.24.01 at Thu Jun 27 23:30:13 CEST 2024.
#
# Compiled from:
#   /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in
#   /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.init.in
#   genConfig/protodunedm-generated-config.cmake.vars.in
#   genConfig/protodunedm-generated-config.cmake.deps.in
#   genConfig/protodunedm-generated-config.cmake.targets.in
#   genConfig/protodunedm-generated-config.cmake.target_vars.in
#   /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
########################################################################
###INCLUDE_END###   /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.preamble.in

###INCLUDE_BEGIN### /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.init.in (2 passes)
###############################################################################
####### Expanded from @PACKAGE_INIT@ by configure_package_config_file() #######
####### Any changes to this file will be overwritten by the next CMake run ####
####### The input file was protodunedmConfig.cmake.in                            ########

get_filename_component(PACKAGE_PREFIX_DIR "${CMAKE_CURRENT_LIST_DIR}/../../../../" ABSOLUTE)

macro(set_and_check _var _file)
  set(${_var} "${_file}")
  if(NOT EXISTS "${_file}")
    message(FATAL_ERROR "File or directory ${_file} referenced by variable ${_var} does not exist !")
  endif()
endmacro()

macro(check_required_components _NAME)
  foreach(comp ${${_NAME}_FIND_COMPONENTS})
    if(NOT ${_NAME}_${comp}_FOUND)
      if(${_NAME}_FIND_REQUIRED_${comp})
        set(${_NAME}_FOUND FALSE)
      endif()
    endif()
  endforeach()
endmacro()

####################################################################################

# Make find_dependency() macro available.
include(CMakeFindDependencyMacro)
###INCLUDE_END###   /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.init.in

###INCLUDE_BEGIN### genConfig/protodunedm-generated-config.cmake.vars.in
####################################
# Package variable definitions.
####################################
# protodunedm_NAMESPACE
set(protodunedm_NAMESPACE "protodunedm")
# protodunedm_INCLUDE_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/include")
  file(GLOB _protodunedm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/include/*")
  if (_protodunedm_TMP_DIR_ENTRIES)
    set_and_check(protodunedm_INCLUDE_DIR "${PACKAGE_PREFIX_DIR}/include")
  endif()
  unset(_protodunedm_TMP_DIR_ENTRIES)
endif()
# protodunedm_LIBRARY_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  file(GLOB _protodunedm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib/*")
  if (_protodunedm_TMP_DIR_ENTRIES)
    set_and_check(protodunedm_LIBRARY_DIR "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  endif()
  unset(_protodunedm_TMP_DIR_ENTRIES)
endif()
# protodunedm_BIN_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin")
  file(GLOB _protodunedm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin/*")
  if (_protodunedm_TMP_DIR_ENTRIES)
    set_and_check(protodunedm_BIN_DIR "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/bin")
  endif()
  unset(_protodunedm_TMP_DIR_ENTRIES)
endif()
# protodunedm_INSTALLED_SOURCE_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/source")
  file(GLOB _protodunedm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/source/*")
  if (_protodunedm_TMP_DIR_ENTRIES)
    set_and_check(protodunedm_INSTALLED_SOURCE_DIR "${PACKAGE_PREFIX_DIR}/source")
  endif()
  unset(_protodunedm_TMP_DIR_ENTRIES)
endif()
# protodunedm_FHICL_DIR
if (EXISTS "${PACKAGE_PREFIX_DIR}/fcl")
  file(GLOB _protodunedm_TMP_DIR_ENTRIES "${PACKAGE_PREFIX_DIR}/fcl/*")
  if (_protodunedm_TMP_DIR_ENTRIES)
    set_and_check(protodunedm_FHICL_DIR "${PACKAGE_PREFIX_DIR}/fcl")
  endif()
  unset(_protodunedm_TMP_DIR_ENTRIES)
endif()

####################################
# Package include directories.
####################################
if (IS_DIRECTORY "${PACKAGE_PREFIX_DIR}/include")
  # CMake convention:
  set(protodunedm_INCLUDE_DIRS "${PACKAGE_PREFIX_DIR}/include")
endif()

####################################
# Package library directories.
####################################
if (IS_DIRECTORY "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
  # CMake convention:
  set(protodunedm_LIBRARY_DIRS "${PACKAGE_PREFIX_DIR}/slf7.x86_64.e26.prof/lib")
endif()
###INCLUDE_END###   genConfig/protodunedm-generated-config.cmake.vars.in

###INCLUDE_BEGIN### genConfig/protodunedm-generated-config.cmake.deps.in
####################################
# Transitive dependencies.
####################################
set(_protodunedm_PACKAGE_PREFIX_DIR "${PACKAGE_PREFIX_DIR}")
find_dependency(larsoft REQUIRED)
find_dependency(nutools REQUIRED)
find_dependency(art REQUIRED)
set(PACKAGE_PREFIX_DIR "${_protodunedm_PACKAGE_PREFIX_DIR}")
unset(_protodunedm_PACKAGE_PREFIX_DIR)
###INCLUDE_END###   genConfig/protodunedm-generated-config.cmake.deps.in

###INCLUDE_BEGIN### genConfig/protodunedm-generated-config.cmake.targets.in
####################################
# Exported targets, and package components.
####################################

##################
# Automatically-generated runtime targets: protodunedm
##################
include("${CMAKE_CURRENT_LIST_DIR}/protodunedmTargets.cmake")
foreach (component IN LISTS protodunedm_FIND_COMPONENTS)
  include("${CMAKE_CURRENT_LIST_DIR}/protodunedmTargets_${component}.cmake")
endforeach()
###INCLUDE_END###   genConfig/protodunedm-generated-config.cmake.targets.in

###INCLUDE_BEGIN### genConfig/protodunedm-generated-config.cmake.target_vars.in
####################################
# Old cetbuildtools-style target variables.
####################################
if (${CETMODULES_CURRENT_PROJECT_NAME}_OLD_STYLE_CONFIG_VARS OR # Per-dependent setting.
 cetbuildtools_UPS_VERSION OR # Backward-compatibility.
 ${CETMODULES_CURRENT_PROJECT_NAME}_UPS_BUILD_ONLY_DEPENDENCIES
 MATCHES "(^|;)cetbuildtools(;|$)")
  set(PROTODUNEDM_HEPMCFILEGEN_MODULE protodunedm::HepMCFileGen_module)
  set(PROTODUNEDM_PROTODUNEDMANALYZE_MODULE protodunedm::ProtoDUNEDMAnalyze_module)
  set(PROTODUNEDM_TRIGGERPRIMITIVEPROTODUNE_MODULE protodunedm::TriggerPrimitiveProtoDUNE_module)
endif()
###INCLUDE_END###   genConfig/protodunedm-generated-config.cmake.target_vars.in

###INCLUDE_BEGIN### /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
# Check package components.
check_required_components(protodunedm)
###INCLUDE_END###   /cvmfs/larsoft.opensciencegrid.org/products/cetmodules/v3_24_01/config/package-config.cmake.bottom.in
